version: 2.1

jobs:
  environ:
    parameters:
      db:
        type: string
      experimental:
        type: string
        default: ""
    machine:
      image: ubuntu-2204:2023.04.2
    environment:
      MIRRORCACHE_DB_PROVIDER: << parameters.db >>
      T_EXPERIMENTAL: << parameters.experimental >>
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run:
          command: |
            echo '{ "ipv6": true,  "fixed-cidr-v6": "fd00::/80" }' | sudo tee /etc/docker/daemon.json
            sudo systemctl restart docker
      - run: make test_docker

workflows:
  version: 2.1
  test:
    jobs:
      - environ:
          db: postgresql
          name: "t: psql"
          filters:
            branches:
              ignore: gh-pages
      - environ:
          db: mariadb
          name: "t: mariadb"
          filters:
            branches:
              ignore: gh-pages
      - environ:
          db: mariadb
          experimental: "1"
          name: "t: mariadb experimental"
          filters:
            branches:
              ignore: gh-pages
