version: 2.1

jobs:
  environ:
    machine:
      image: ubuntu-2004:202008-01
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run:
          command: |
            echo '{ "ipv6": true,  "fixed-cidr-v6": "fd00::/80" }' | sudo tee /etc/docker/daemon.json
            sudo systemctl restart docker
      - run: make test_docker

  systemd:
    machine:
      image: ubuntu-2004:202008-01
    environment:
      PRIVILEGED_TESTS: 1
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run: make test_systemd

workflows:
  version: 2.1
  test:
    jobs:
      - environ
      - systemd
