FROM opensuse/leap:16.0
ENV container docker

ENV LANG en_US.UTF-8

RUN sed -i 's,http://download.opensuse.org,http://cdn.opensuse.org,g' /etc/zypp/repos.d/*repo
RUN zypper ar -f http://cdn.opensuse.org/repositories/openSUSE:infrastructure:MirrorCache/16.0 mc
RUN zypper --gpg-auto-import-keys ref

# install MirrorCache here to fetch all dependencies
RUN zypper -vvv -n install MirrorCache perl-MaxMind-DB-Reader perl-Mojolicious-Plugin-ClientIP \
    vim mariadb mariadb-server curl sudo git-core wget tar m4 make rsync \
    apache2 perl-Digest-MD4 tidy nginx perl-DBD-mysql perl-Mojo-mysql perl-Minion-Backend-mysql perl-DateTime-HiRes \
    perl-Config-IniFiles environ eatmydata which

# optional dependencies used in testing
RUN zypper -vvv -n install perl-Geo-IP2Location perl-Digest-Zsync perl-DateTime-Format-MySQL libxml2-tools iputils findutils systemd

WORKDIR /opt/project
ENV TZ UTC
ENV MOJO_PUBSUB_EXPERIMENTAL 1

# see MDEV-39860
RUN systemd-tmpfiles --create /usr/lib/tmpfiles.d/mariadb.conf

ENTRYPOINT ["/usr/bin/tail", "-f", "/dev/null"]
