FROM opensuse/leap:16.0
ENV container docker

ENV LANG en_US.UTF-8

RUN zypper ar -f http://cdn.opensuse.org/repositories/openSUSE:infrastructure:MirrorCache/16.0 mc
RUN zypper --gpg-auto-import-keys ref

# install MirrorCache here to fetch all dependencies
RUN zypper -vvv -n install MirrorCache perl-MaxMind-DB-Reader perl-Mojolicious-Plugin-ClientIP \
    vim postgresql postgresql-server curl sudo git-core wget tar m4 make rsync \
    apache2 perl-Digest-MD4 tidy nginx perl-DateTime-HiRes perl-Config-IniFiles environ

# optional dependencies used in testing
RUN zypper -vvv -n install perl-Geo-IP2Location perl-Digest-Zsync libxml2-tools iputils findutils

WORKDIR /opt/project
ENV TZ UTC

ENTRYPOINT ["/usr/bin/tail", "-f", "/dev/null"]
