FROM opensuse/leap:16.0
ENV container docker

ENV LANG en_US.UTF-8

RUN zypper -n in curl # rpm --import needs curl atm
RUN curl -IL https://mirror.mariadb.org/yum/11.8/sles15-amd64/repodata/repomd.xml
RUN zypper ar -f http://cdn.opensuse.org/repositories/openSUSE:infrastructure:MirrorCache/16.0 mc
# RUN zypper ar -f https://mirror.mariadb.org/yum/11.8/sles15-amd64 mariadb
RUN zypper ar -f https://mirror.netcologne.de/mariadb/mariadb-11.8.8/yum/sles/16.0/x86_64 mariadb
RUN rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
RUN zypper --gpg-auto-import-keys ref

# install MirrorCache here to fetch all dependencies
RUN zypper -vvv -n install MirrorCache perl-MaxMind-DB-Reader perl-Mojolicious-Plugin-ClientIP \
    vim MariaDB-server MariaDB-client curl sudo git-core wget tar m4 make rsync \
    apache2 perl-Digest-MD4 tidy nginx perl-DBD-mysql perl-Mojo-mysql perl-Minion-Backend-mysql perl-DateTime-HiRes \
    perl-Config-IniFiles environ eatmydata which

# optional dependencies used in testing
RUN zypper -vvv -n install perl-Geo-IP2Location perl-Digest-Zsync perl-DateTime-Format-MySQL libxml2-tools iputils findutils

RUN zypper -vvv -n install MariaDB-server-compat MariaDB-client-compat

WORKDIR /opt/project
ENV TZ UTC
ENV MOJO_PUBSUB_EXPERIMENTAL 1


ENTRYPOINT ["/usr/bin/tail", "-f", "/dev/null"]
